### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by sawatzkylindsey** [767-lvl/nn-wd#13]
As originally sketched, lets allow for sections of operations to be "zoomed" in on where it fills out a bigger portion and we can see the weights more clearly

**Comment by sawatzkylindsey** [comment]
In thinking about this more, maybe we shouldn't do what I had originally sketched.  How about we start by simply doing a more classical zoom, which makes the portion clicked bigger by drawing a blown up version of them on-top of the existing visualization.  The blown up portion should be about as big as necessary to just slightly cover its surrounding elements, but not completely cover them.

So roughly 2x zoom.

**Comment by vladymyrkozyr** [comment]
I added global zooming to svg element for now. Then I can add it on click of a particular part of the screen

**Comment by sawatzkylindsey** [comment]
So I checked this out, and unfortunately I don't think its what we want for zoom.  The problem is, we want to be able to visualize an aspect of the NN in more detail, while at the same time still seeing everything else such as the input and output.

Can we try doing a zoom like I had originally diagrammed?  We'd probably just need to draw a white box on top of the existing elements, and then inside the white box draw the zoomed portion.  The white box should be big enough to maybe just barely start to cover its surrounding elements, but not completely surround them.

**Comment by sawatzkylindsey** [comment]
Let me know if you
